# Generated by Django 5.0.2 on 2025-02-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_rename_user_1_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proba_text', models.TextField(default='прекрасное фото', max_length=256)),
            ],
            options={
                'verbose_name': 'Проба',
            },
        ),
    ]
