# Generated by Django 5.0.2 on 2025-02-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_proba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proba',
            options={'verbose_name': 'Проба', 'verbose_name_plural': 'Пробы пера'},
        ),
    ]
