# Generated by Django 5.1.7 on 2025-03-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_proba_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_1',
            old_name='created_at',
            new_name='created_at_1',
        ),
        migrations.RenameField(
            model_name='post_1',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='post_1',
            old_name='user',
            new_name='user_1',
        ),
    ]
