# Generated by Django 5.1.7 on 2025-03-10 07:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_rename_created_at_post_1_created_at_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proba',
            options={'verbose_name': 'Вывод с комментапиями', 'verbose_name_plural': 'Вывод с комментапиями'},
        ),
        migrations.RenameField(
            model_name='proba',
            old_name='proba_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='proba',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='proba',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='proba',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
