# Generated by Django 5.1.7 on 2025-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_remove_proba_user_alter_post_user_delete_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
